spring.application.name=pizzeria-web

# Port de l'application Web (pour ne pas entrer en conflit avec l'API)
server.port=8081

# Configuration Thymeleaf (Désactiver le cache en développement pour voir les modifs CSS/HTML en temps réel)
spring.thymeleaf.cache=false

# URL de l'API REST
com.resto.pizzeria.web.apiUrl=http://localhost:8080/api
